#!/bin/sh
case "$1" in
  start)
	printf "Mounting host directory: "
	mount -t 9p -o trans=virtio host /mnt
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Unmounting host directory: "
	umount /mnt
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

